[package]
edition = "2024"
name = "algos"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
algos_core = { version = "0.1.0", path = "algos_core" }
cpal = "0.15.3"
derivative = "2.2.0"
dirs = "5.0.1"
file-rotate = "0.7.6"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.2", default-features = false, features = [
    "napi9",
    "tokio_rt",
    "compat-mode",
    "serde-json",
] }
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi-derive = "2.12.2"
napi_derive_ext = { version = "0.1.0", path = "napi_derive_ext" }
serde = { version = "1.0.210", features = ["serde_derive"] }
serde_with = "3.9.0"
slog = "2.7.0"
slog-async = "2.8.0"
slog-term = "2.9.1"
strum = { version = "0.26.3", features = ["derive"] }
tokio = "1.40.0"
tokio-util = "0.7.12"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
strip = "symbols"
