/* automatically generated by rust-bindgen 0.70.1 */

use std::sync::LazyLock;

#[cfg(windows)]
pub const DiscordFrameType_DISCORD_FRAME_NATIVE: DiscordFrameType = 0;
pub const DiscordFrameType_DISCORD_FRAME_I420: DiscordFrameType = 1;
pub type DiscordFrameType = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DiscordYuvFrame {
	pub y: *const u8,
	pub u: *const u8,
	pub v: *const u8,
	pub y_stride: i32,
	pub u_stride: i32,
	pub v_stride: i32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
	["Size of DiscordYUVFrame"][::std::mem::size_of::<DiscordYuvFrame>() - 40usize];
	["Alignment of DiscordYUVFrame"][::std::mem::align_of::<DiscordYuvFrame>() - 8usize];
	["Offset of field: DiscordYUVFrame::y"][::std::mem::offset_of!(DiscordYuvFrame, y) - 0usize];
	["Offset of field: DiscordYUVFrame::u"][::std::mem::offset_of!(DiscordYuvFrame, u) - 8usize];
	["Offset of field: DiscordYUVFrame::v"][::std::mem::offset_of!(DiscordYuvFrame, v) - 16usize];
	["Offset of field: DiscordYUVFrame::y_stride"]
		[::std::mem::offset_of!(DiscordYuvFrame, y_stride) - 24usize];
	["Offset of field: DiscordYUVFrame::u_stride"]
		[::std::mem::offset_of!(DiscordYuvFrame, u_stride) - 28usize];
	["Offset of field: DiscordYUVFrame::v_stride"]
		[::std::mem::offset_of!(DiscordYuvFrame, v_stride) - 32usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct DiscordFrame {
	pub timestamp_us: i64,
	pub frame: DiscordFrame__bindgen_ty_1,
	pub width: i32,
	pub height: i32,
	pub type_: i32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union DiscordFrame__bindgen_ty_1 {
	pub yuv: DiscordYuvFrame,
	#[cfg(windows)]
	pub texture_handle: *mut ::windows::Win32::Foundation::HANDLE,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
	["Size of DiscordFrame__bindgen_ty_1"]
		[::std::mem::size_of::<DiscordFrame__bindgen_ty_1>() - 40usize];
	["Alignment of DiscordFrame__bindgen_ty_1"]
		[::std::mem::align_of::<DiscordFrame__bindgen_ty_1>() - 8usize];
	["Offset of field: DiscordFrame__bindgen_ty_1::yuv"]
		[::std::mem::offset_of!(DiscordFrame__bindgen_ty_1, yuv) - 0usize];
	#[cfg(windows)]
	["Offset of field: DiscordFrame__bindgen_ty_1::texture_handle"]
		[::std::mem::offset_of!(DiscordFrame__bindgen_ty_1, texture_handle) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
	["Size of DiscordFrame"][::std::mem::size_of::<DiscordFrame>() - 64usize];
	["Alignment of DiscordFrame"][::std::mem::align_of::<DiscordFrame>() - 8usize];
	["Offset of field: DiscordFrame::timestamp_us"]
		[::std::mem::offset_of!(DiscordFrame, timestamp_us) - 0usize];
	["Offset of field: DiscordFrame::frame"][::std::mem::offset_of!(DiscordFrame, frame) - 8usize];
	["Offset of field: DiscordFrame::width"][::std::mem::offset_of!(DiscordFrame, width) - 48usize];
	["Offset of field: DiscordFrame::height"]
		[::std::mem::offset_of!(DiscordFrame, height) - 52usize];
	["Offset of field: DiscordFrame::type_"][::std::mem::offset_of!(DiscordFrame, type_) - 56usize];
};
pub type DiscordFrameReleaseCB =
	::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>;

#[cfg(not(windows))]
extern "C" {
	pub fn DeliverDiscordFrame(
		streamId: *const ::std::os::raw::c_char,
		frame: *const DiscordFrame,
		releaseCB: DiscordFrameReleaseCB,
		userData: *mut ::std::os::raw::c_void,
	);
}

#[cfg(windows)]
pub static DeliverDiscordFrame: LazyLock<
	extern "C" fn(
		streamId: *const ::std::os::raw::c_char,
		frame: *const DiscordFrame,
		releaseCB: DiscordFrameReleaseCB,
		userData: *mut ::std::os::raw::c_void,
	),
> = LazyLock::new(|| unsafe {
	let lib = libloading::os::windows::Library::this().unwrap();

	*lib.get(b"DeliverDiscordFrame").unwrap()
});
