[package]
name = "algos_core"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
atomic_float = "1.1.0"
byteorder = "1.5.0"
cpal = { version = "0.15.3", features = ["asio", "jack"] }
discord-electron = { version = "0.1.0", path = "discord-electron" }
discortp = "0.6.0"
flume = "0.11.0"
futures = "0.3.31"
glib = "0.20.4"
gst = { package = "gstreamer", version = "0.23.2" }
gst-app = { package = "gstreamer-app", version = "0.23.2" }
gst-base = { version = "0.23.2", package = "gstreamer-base" }
gst-rtp = { version = "0.23.2", package = "gstreamer-rtp" }
opus = "0.3.0"
parking_lot = "0.12.3"
rtrb = "0.3.1"
samplerate = "0.2.4"
serde = { version = "1.0.210", features = ["derive"] }
serde_with = "3.11.0"
slog = "2.7.0"
sloggers = "2.2.0"
static_assertions_next = "1.1.2"
strum = { version = "0.26.3", features = ["derive"] }
tokio = { version = "1.40.0", features = [
    "macros",
    "net",
    "parking_lot",
    "rt-multi-thread",
    "sync",
    "time",
] }
tokio-util = "0.7.12"
